---
name: booklyapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  go_router: ^10.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.7
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
